
#!/usr/bin/env python3
"""
select_best_episodes.py

Read a CSV of episode metrics (expects columns: 'episode', 'psnr_mean', 'ssim_mean', optional 'saved_dir')
and output the best episodes according to several selection strategies.

Strategies:
  - psnr:        Top-K (or top percentile) by PSNR only.
  - ssim:        Top-K (or top percentile) by SSIM only.
  - rank:        Average of ranks across PSNR and SSIM (lower avg rank is better).
  - composite:   Weighted composite score after normalization (zscore or minmax): score = w_psnr*PSNR_norm + w_ssim*SSIM_norm.
  - pareto:      Pareto-optimal set where no episode is dominated on BOTH metrics (higher is better for both).
                 If K is provided and Pareto set > K, fall back to 'composite' to pick top-K from Pareto set.

You can specify either --k or --percentile. If both are omitted, defaults to --k 100.
If both are provided, --k takes precedence.

Example usage:
  python select_best_episodes.py --csv runs/coinrun/genie_summary.csv --method composite --k 100 --out best_episodes.csv
  python select_best_episodes.py --csv runs/coinrun/genie_summary.csv --method pareto --out pareto_front.csv
  python select_best_episodes.py --csv runs/coinrun/genie_summary.csv --method joint_and --percentile 25 --out top25_both.csv

Author: generated by ChatGPT
"""

import argparse
import sys
from pathlib import Path
import pandas as pd
import numpy as np

def _ensure_numeric(df: pd.DataFrame, cols):
    for c in cols:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
        else:
            raise KeyError(f"Missing required column '{c}' in CSV.")
    return df

def _normalize(series: pd.Series, mode: str = "zscore"):
    if mode == "zscore":
        mu, sigma = series.mean(), series.std(ddof=0)
        if sigma == 0 or np.isnan(sigma):
            # All equal -> return zeros to avoid NaNs
            return pd.Series(np.zeros(len(series)), index=series.index)
        return (series - mu) / sigma
    elif mode == "minmax":
        lo, hi = series.min(), series.max()
        if hi == lo:
            return pd.Series(np.zeros(len(series)), index=series.index)
        return (series - lo) / (hi - lo)
    else:
        raise ValueError("normalize must be one of {'zscore','minmax'}")

def _avg_rank(df: pd.DataFrame):
    # rank: highest value gets rank 1
    r_psnr = df['psnr_mean'].rank(ascending=False, method='average')
    r_ssim = df['ssim_mean'].rank(ascending=False, method='average')
    avg_r = (r_psnr + r_ssim) / 2.0
    return r_psnr, r_ssim, avg_r

def _pareto_front_indices(psnr: pd.Series, ssim: pd.Series):
    """
    Return boolean mask of Pareto-optimal points for maximizing both psnr and ssim.
    Efficient skyline in 2D: sort by psnr desc, sweep keeping best ssim so far.
    """
    order = np.argsort(-psnr.values, kind='mergesort')  # stable desc by PSNR
    best_ssim = -np.inf
    is_pareto = np.zeros(len(psnr), dtype=bool)
    for idx in order:
        val_ssim = ssim.iloc[idx]
        if val_ssim >= best_ssim:
            is_pareto[idx] = True
            best_ssim = val_ssim
    return pd.Series(is_pareto, index=psnr.index)

def select(df: pd.DataFrame,
           method: str = "composite",
           k: int = 100,
           percentile: float = None,
           normalize: str = "zscore",
           w_psnr: float = 0.5,
           w_ssim: float = 0.5,
           joint_kind: str = None):
    """
    Core selection logic.
    """
    # Basic validation
    df = df.copy()
    df = _ensure_numeric(df, ["psnr_mean", "ssim_mean"])
    df = df.dropna(subset=["psnr_mean", "ssim_mean"]).reset_index(drop=True)

    # Determine how many to select
    n = len(df)
    if percentile is not None and (percentile <= 0 or percentile >= 100):
        raise ValueError("--percentile must be in (0, 100)")
    if k is None and percentile is None:
        k = min(100, n)  # default

    # Helper to translate percentile to count
    def _count_from_percentile(p):
        return max(1, int(np.ceil(n * (p / 100.0))))

    # Joint strategies (AND/OR of individual top-percentile)
    if method in {"joint_and", "joint_or"}:
        if percentile is None:
            percentile = 25.0  # sensible default
        k_psnr = _count_from_percentile(percentile)
        k_ssim = _count_from_percentile(percentile)

        top_psnr_idx = df['psnr_mean'].nlargest(k_psnr).index
        top_ssim_idx = df['ssim_mean'].nlargest(k_ssim).index

        if method == "joint_and":
            chosen_idx = sorted(set(top_psnr_idx).intersection(set(top_ssim_idx)))
        else:
            chosen_idx = sorted(set(top_psnr_idx).union(set(top_ssim_idx)))

        sel = df.loc[chosen_idx].copy()
        sel['rank_psnr'] = df['psnr_mean'].rank(ascending=False, method='min')
        sel['rank_ssim'] = df['ssim_mean'].rank(ascending=False, method='min')
        sel['selected_by'] = method
        sel = sel.sort_values(['rank_psnr', 'rank_ssim']).reset_index(drop=True)
        return sel

    if method == "psnr":
        if percentile is not None:
            k = _count_from_percentile(percentile)
        sel = df.nlargest(k, 'psnr_mean').copy()
        sel['rank_psnr'] = df['psnr_mean'].rank(ascending=False, method='min')
        sel['selected_by'] = "psnr"
        return sel.reset_index(drop=True)

    if method == "ssim":
        if percentile is not None:
            k = _count_from_percentile(percentile)
        sel = df.nlargest(k, 'ssim_mean').copy()
        sel['rank_ssim'] = df['ssim_mean'].rank(ascending=False, method='min')
        sel['selected_by'] = "ssim"
        return sel.reset_index(drop=True)

    if method == "rank":
        r_psnr, r_ssim, avg_r = _avg_rank(df)
        df2 = df.copy()
        df2['rank_psnr'] = r_psnr
        df2['rank_ssim'] = r_ssim
        df2['avg_rank'] = avg_r
        if percentile is not None:
            k = _count_from_percentile(percentile)
        sel = df2.nsmallest(k, 'avg_rank').copy()
        sel['selected_by'] = "rank"
        return sel.reset_index(drop=True)

    if method == "composite":
        psnr_n = _normalize(df['psnr_mean'], normalize)
        ssim_n = _normalize(df['ssim_mean'], normalize)
        score = w_psnr * psnr_n + w_ssim * ssim_n
        df2 = df.copy()
        df2['psnr_norm'] = psnr_n
        df2['ssim_norm'] = ssim_n
        df2['score'] = score
        if percentile is not None:
            k = _count_from_percentile(percentile)
        sel = df2.nlargest(k, 'score').copy()
        sel['selected_by'] = f"composite_{normalize}_w{w_psnr:.2f}_{w_ssim:.2f}"
        return sel.reset_index(drop=True)

    if method == "pareto":
        mask = _pareto_front_indices(df['psnr_mean'], df['ssim_mean'])
        pareto_df = df[mask].copy()
        pareto_df['is_pareto'] = True
        # If k is provided and Pareto set is larger, fall back to composite on Pareto set
        if percentile is not None and k is None:
            k = _count_from_percentile(percentile)
        if k is not None and len(pareto_df) > k:
            psnr_n = _normalize(pareto_df['psnr_mean'], normalize)
            ssim_n = _normalize(pareto_df['ssim_mean'], normalize)
            score = w_psnr * psnr_n + w_ssim * ssim_n
            pareto_df = pareto_df.assign(score=score).nlargest(k, 'score')
            pareto_df['selected_by'] = f"pareto_then_composite_{normalize}_w{w_psnr:.2f}_{w_ssim:.2f}"
            return pareto_df.reset_index(drop=True)
        else:
            pareto_df['selected_by'] = "pareto"
            return pareto_df.sort_values(['psnr_mean','ssim_mean'], ascending=False).reset_index(drop=True)

    raise ValueError(f"Unknown method '{method}'. Choose from psnr, ssim, rank, composite, pareto, joint_and, joint_or.")

def main():
    p = argparse.ArgumentParser(description="Select best episodes from CSV of metrics.")
    p.add_argument("--csv", required=True, help="Path to input CSV (must contain psnr_mean and ssim_mean).")
    p.add_argument("--out", default=None, help="Path to write selected episodes CSV. Defaults to <csv_basename>_selected.csv")
    p.add_argument("--method", default="composite",
                   choices=["psnr", "ssim", "rank", "composite", "pareto", "joint_and", "joint_or"],
                   help="Selection strategy.")
    p.add_argument("--k", type=int, default=None, help="Top-K to select (overrides --percentile if both given).")
    p.add_argument("--percentile", type=float, default=None, help="Top percentile to select (e.g., 25 for top 25%%).")
    p.add_argument("--normalize", default="zscore", choices=["zscore","minmax"],
                   help="Normalization used for 'composite' and Pareto tie-break.")
    p.add_argument("--w_psnr", type=float, default=0.5, help="Weight for PSNR in composite score.")
    p.add_argument("--w_ssim", type=float, default=0.5, help="Weight for SSIM in composite score.")
    args = p.parse_args()

    in_path = Path(args.csv)
    if not in_path.exists():
        print(f"[ERROR] CSV not found: {in_path}", file=sys.stderr)
        sys.exit(2)

    df = pd.read_csv(in_path)
    # Soft check for required columns
    missing = [c for c in ['psnr_mean','ssim_mean'] if c not in df.columns]
    if missing:
        print(f"[ERROR] Missing required columns in CSV: {missing}", file=sys.stderr)
        sys.exit(3)

    selected = select(df,
                      method=args.method,
                      k=args.k,
                      percentile=args.percentile,
                      normalize=args.normalize,
                      w_psnr=args.w_psnr,
                      w_ssim=args.w_ssim)

    # Choose output path
    out_path = Path(args.out) if args.out else in_path.with_name(in_path.stem + "_selected.csv")
    selected.to_csv(out_path, index=False)

    # Pretty print a short summary
    k_final = len(selected)
    how = selected['selected_by'].iloc[0] if len(selected) else args.method
    print(f"[OK] Selected {k_final} episodes using '{how}'. Saved → {out_path}")
    # Show a small preview
    preview_cols = [c for c in ["episode","saved_dir","psnr_mean","ssim_mean","score","avg_rank","rank_psnr","rank_ssim","is_pareto"] if c in selected.columns]
    print(selected[preview_cols].head(10).to_string(index=False))

if __name__ == "__main__":
    main()
