#!/usr/bin/env python3
"""
Evaluate SB3 policy weights (.zip) *inside* the Genie/GenieRedux world model (closed loop).

- Actions are chosen by the SB3 policy from the current WM frame.
- Next frame is generated by the WM (Genie).
- Reward = your FLOW-odometry goal progress (same math as in training script).
- Outputs: GIF + PNG per episode, CSV with episode returns.

Example:
python eval_ppo_in_genie_wm.py \
  --config path/to/world_model.yaml \
  --model_ckpt path/to/world_model.pth \
  --ppo_zip path/to/ppo_agent.zip \
  --init_npz_glob "dataset/*.npz" \
  --episodes 10 --max_steps 256 \
  --save_root runs_wm_eval \
  --dataset_name coinrun \
  --model_name GenieRedux_Guided_CoinRun_80mln_v1.0 \
  --transpose_nchw \
  --goal_screens 1.0 --goal_radius 0.05

"""

from __future__ import annotations
from pathlib import Path
from typing import List, Tuple, Optional, Dict
import argparse
import csv
import glob
import heapq
import random
import sys
import traceback

import numpy as np
import torch
import torch.nn.functional as F
import cv2
from PIL import Image

# SB3
from stable_baselines3 import PPO, A2C
from sb3_contrib import RecurrentPPO

# Project utils
from omegaconf import OmegaConf
from models import construct_model
from data.data import video_tensor_to_gif, video_tensor_to_pil_images


# --------------------------- Small helpers ---------------------------

def _to_chw(img_hwc: np.ndarray) -> torch.Tensor:
    """H×W×C (uint8/float) → CHW float in [0,1]."""
    if img_hwc.dtype not in (np.float32, np.float64):
        x = torch.from_numpy(img_hwc.astype(np.uint8)).permute(2, 0, 1).float() / 255.0
    else:
        x = torch.from_numpy(img_hwc).permute(2, 0, 1).float()
        if x.max() > 1.0:
            x = x / 255.0
    return x

def _resize_chw(x_chw: torch.Tensor, size_hw: Tuple[int, int]) -> torch.Tensor:
    return F.interpolate(x_chw.unsqueeze(0), size=size_hw, mode="bilinear", align_corners=False).squeeze(0)

def frames_to_video_tensor(frames: List[np.ndarray], target_hw: Tuple[int,int]) -> torch.Tensor:
    """List of HWC uint8 → C×T×H×W float[0,1] resized to target_hw."""
    Ht, Wt = target_hw
    outs = []
    for f in frames:
        x = _to_chw(f)
        if f.shape[0] != Ht or f.shape[1] != Wt:
            x = _resize_chw(x, (Ht, Wt))
        outs.append(x)
    vid = torch.stack(outs, dim=1)  # C×T×H×W
    return vid.clamp(0,1)

def save_row_gif_png(out_dir: Path, base: str, row_video: torch.Tensor) -> None:
    """
    Save a single-row GIF/PNG for a rollout.
    row_video: C×T×H×W
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    gif_path = out_dir / f"{base}.gif"
    video_tensor_to_gif(row_video.cpu(), str(gif_path))

    # contact sheet (one row across time)
    row_img = video_tensor_to_pil_images(row_video.cpu(), only_first_image=False)
    row_img.save(out_dir / f"{base}.png")

def load_cfg(cfg_path: str):
    return OmegaConf.load(cfg_path)

def _maybe_extract(sd: dict, keys: List[str]) -> Optional[dict]:
    if not isinstance(sd, dict): return None
    for k in keys:
        if k in sd and isinstance(sd[k], dict):
            return sd[k]
    return None

def build_world_model(cfg, ckpt_path: str, device: torch.device, tokenizer_ckpt: Optional[str] = None):
    model = construct_model(cfg)
    sd = torch.load(ckpt_path, map_location="cpu")
    cand = _maybe_extract(sd, ["model", "state_dict"])
    if cand is not None:
        sd = cand
    model.load_state_dict(sd, strict=False)

    if tokenizer_ckpt:
        tsd = torch.load(tokenizer_ckpt, map_location="cpu")
        cand_tok = _maybe_extract(tsd, ["tokenizer","model","state_dict"]) or tsd
        try:
            model.tokenizer.load_state_dict(cand_tok, strict=False)
            print("[Tokenizer] Loaded separate tokenizer checkpoint.")
        except Exception as e:
            print(f"[Tokenizer][WARN] Could not load tokenizer: {e}")

    model.eval().to(device)

    # image size
    try:
        image_size = model.image_size
        if isinstance(image_size, int):
            image_size = (image_size, image_size)
    except Exception:
        image_size = (64, 64)

    # capacities
    tokens_per_frame = getattr(model.tokenizer, "image_num_tokens", None)
    max_seq_len = getattr(getattr(model.dynamics, "maskgit", None), "max_seq_len", None)
    action_dim = getattr(getattr(model.dynamics, "maskgit", None), "action_dim", None)
    if tokens_per_frame is None or max_seq_len is None or action_dim is None:
        raise RuntimeError("Model missing tokenizer.image_num_tokens, dynamics.maskgit.max_seq_len, or action_dim.")
    max_frames = max(1, max_seq_len // tokens_per_frame)

    return model, (int(image_size[0]), int(image_size[1])), int(action_dim), int(max_frames)

# ---------- optical flow + ROI (same math as training) ----------

def _downscale_to_longside(gray: np.ndarray, longside: int) -> np.ndarray:
    H, W = gray.shape
    if longside is None or max(H, W) == longside:
        return gray
    s = float(longside) / float(max(H, W))
    new_size = (max(8, int(W * s)), max(8, int(H * s)))
    return cv2.resize(gray, new_size, interpolation=cv2.INTER_AREA)

def _flow_residual(prev_gray: np.ndarray, next_gray: np.ndarray, *, longside: int = 64, baseline: str = "sky"):
    p = _downscale_to_longside(prev_gray, longside)
    n = _downscale_to_longside(next_gray, longside)
    flow = cv2.calcOpticalFlowFarneback(p, n, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    fx, fy = flow[..., 0], flow[..., 1]
    if baseline == "global":
        fx -= np.median(fx); fy -= np.median(fy)
    elif baseline == "sky":
        h = fx.shape[0]; top = slice(0, max(1, int(0.2 * h)))
        fx -= np.median(fx[top, :]); fy -= np.median(fy[top, :])
    elif baseline == "none":
        pass
    else:
        raise ValueError(f"Unknown baseline: {baseline}")
    return fx, fy

def _roi_weight(H: int, W: int, *, bottom_bias: float,
                roi: Tuple[float, float, float, float]) -> np.ndarray:
    row = np.linspace(0, 1, H, dtype=np.float32)
    wv = 1.0 + (row ** 2) * (bottom_bias - 1.0)
    wv /= max(np.mean(wv), 1e-9)
    weight = np.repeat(wv[:, None], W, axis=1)
    y0, y1, x0, x1 = roi
    iy0, iy1 = int(y0 * H), int(y1 * H)
    ix0, ix1 = int(x0 * W), int(x1 * W)
    mask = np.zeros_like(weight, dtype=np.float32)
    mask[iy0:iy1, ix0:ix1] = 1.0
    return weight * mask

# ---------- prime provider (same as training) ----------

class PrimeProvider:
    def __init__(self, npz_glob: str, image_hw: Tuple[int,int]):
        paths = sorted(glob.glob(npz_glob))
        if not paths:
            raise RuntimeError(f"No NPZs matched for primes: {npz_glob}")
        self.paths = paths
        self.Ht, self.Wt = image_hw

    def sample_prime(self) -> np.ndarray:
        p = random.choice(self.paths)
        with np.load(p, allow_pickle=True) as npz:
            frames = None
            for k in ["frames","videos","input_frames","obs","images","x"]:
                if k in npz:
                    frames = npz[k]; break
            if frames is None:
                for k, v in npz.items():
                    if isinstance(v, np.ndarray) and v.ndim >= 3 and 3 in v.shape:
                        frames = v; break
            if frames is None:
                raise RuntimeError(f"No frames array in {p}")

            f = frames
            # normalize to T×H×W×C
            if f.ndim == 4:
                if f.shape[-1] in (1,3):
                    pass
                elif f.shape[0] in (1,3): f = np.transpose(f, (1,2,3,0))
                elif f.shape[1] in (1,3): f = np.transpose(f, (0,2,3,1))
            elif f.ndim == 5 and f.shape[0] in (1,3):
                f = np.transpose(f, (1,2,3,0))
            else:
                raise RuntimeError(f"Unsupported frames shape in {p}: {frames.shape}")

            f0 = f[0]
            if f0.dtype != np.uint8:
                if np.max(f0) <= 1.0:
                    f0 = (np.clip(f0,0,1)*255).astype(np.uint8)
                else:
                    f0 = np.clip(f0,0,255).astype(np.uint8)

            # resize to WM size
            chw = _to_chw(f0)
            chw = _resize_chw(chw, (self.Ht, self.Wt))
            return (chw.clamp(0,1)*255).byte().permute(1,2,0).cpu().numpy()  # HWC uint8

# --------------------------- Core evaluation loop ---------------------------

def run_one_episode_closed_loop(
    wm,
    policy,
    device: torch.device,
    image_hw: Tuple[int,int],
    provider: PrimeProvider,
    *,
    transpose_nchw: bool,
    inference_steps: int,
    sample_temperature: float,
    mask_schedule: str,
    max_steps: int,
    # reward params
    downscale: int,
    bottom_bias: float,
    roi: Tuple[float,float,float,float],
    flow_baseline: str,
    dx_clip: float,
    dx_smooth: float,
    goal_x: float,
    goal_y: float,
    goal_y_weight: float,
    goal_radius: float,
    success_bonus: float,
    reward_scale: float,
    is_recurrent: bool,
) -> Dict[str, object]:
    """Closed-loop in WM; returns dict with frames, actions, return, etc."""
    Ht, Wt = image_hw

    # prime frame from dataset
    f0 = provider.sample_prime()  # HWC uint8 at WM size
    frames = [f0]
    actions: List[int] = []

    # WM prime tensor
    x0 = _to_chw(f0)
    prime = x0.unsqueeze(0).unsqueeze(2).to(device)  # 1×C×1×H×W

    # odometry state
    xhat = 0.0
    yhat = 0.5
    prev_dx = 0.0
    prev_dy = 0.0
    episode_return = 0.0

    rnn_state = None
    episode_start = np.array([True], dtype=bool)

    for t in range(max_steps):
        # policy obs
        pol_obs = np.transpose(frames[-1], (2,0,1)) if transpose_nchw else frames[-1]
        if is_recurrent:
            a, rnn_state = policy.predict(
                pol_obs,
                state=rnn_state,
                episode_start=episode_start,
                deterministic=False,
            )
            episode_start[:] = False
        else:
            a, _ = policy.predict(pol_obs, deterministic=False)

        if isinstance(a, np.ndarray):
            a = int(a)
        # clip to WM action range if needed
        A = int(getattr(getattr(wm.dynamics, "maskgit", None), "action_dim", 7))
        if a < 0 or a >= A:
            a = max(0, min(a, A-1))

        # WM one-step prediction
        acts = torch.tensor([[a]], dtype=torch.long, device=device)
        with torch.no_grad():
            pred = wm.sample(
                prime_frames=prime,
                actions=acts,
                num_frames=1,
                inference_steps=inference_steps,
                sample_temperature=sample_temperature,
                mask_schedule=mask_schedule,
                return_recons_only=True,
            )  # 1×C×1×H×W

        next_frame = (pred[0, :, 0].clamp(0,1) * 255).byte().permute(1,2,0).cpu().numpy()
        frames.append(next_frame)
        actions.append(a)
        prime = pred[:, :, -1:].detach()

        # reward via FLOW-odometry progress
        p = cv2.cvtColor(frames[-2], cv2.COLOR_RGB2GRAY)
        c = cv2.cvtColor(frames[-1], cv2.COLOR_RGB2GRAY)
        fx_res, fy_res = _flow_residual(p, c, longside=downscale, baseline=flow_baseline)
        Hf, Wf = fx_res.shape
        weight = _roi_weight(Hf, Wf, bottom_bias=bottom_bias, roi=roi)
        denom  = weight.sum() + 1e-9

        dxf_px = float(((-fx_res) * weight).sum() / denom)
        dyf_px = float(((-fy_res) * weight).sum() / denom)
        dx = np.clip(dxf_px / max(Wf, 1), -dx_clip, dx_clip)
        dy = np.clip(dyf_px / max(Hf, 1), -dx_clip, dx_clip)
        # smooth
        dx = (1.0 - dx_smooth) * dx + dx_smooth * prev_dx
        dy = (1.0 - dx_smooth) * dy + dx_smooth * prev_dy
        prev_dx, prev_dy = dx, dy

        x_prev, y_prev = xhat, yhat
        xhat = max(0.0, xhat + dx)
        yhat = float(np.clip(yhat + dy, 0.0, 1.0))

        gx, gy = goal_x, goal_y
        prev_dist = float(np.sqrt((gx - x_prev)**2 + (goal_y_weight*(gy - y_prev))**2))
        dist      = float(np.sqrt((gx - xhat )**2 + (goal_y_weight*(gy - yhat ))**2))
        r = reward_scale * (prev_dist - dist)
        if dist < goal_radius:
            r += success_bonus
        episode_return += float(r)

        # optional: early stop after success (kept simple here)

    # pack results
    return {
        "frames": np.stack(frames, axis=0),       # T×H×W×C
        "actions": np.asarray(actions, np.int64), # (T-1,)
        "return": float(episode_return),
        "len": int(len(actions)),
        "goal": (goal_x, goal_y),
    }

# --------------------------- CLI ---------------------------

def main():
    ap = argparse.ArgumentParser(description="Evaluate PPO .zip inside Genie world model (closed loop)")
    # WM
    ap.add_argument("--config", default="/home/sdainelli/Aladdin/neurIPS/configs/config/guided_genie_config.yaml", help="Hydra config .yaml for world model")
    ap.add_argument("--model_ckpt", default="/home/sdainelli/Aladdin/neurIPS/checkpoints/GenieRedux_Guided_CoinRun_80mln_v1.0/model.pt", help="World model checkpoint (.pt/.pth)")
    ap.add_argument("--tokenizer_ckpt", default=None, help="Optional separate tokenizer checkpoint")
    ap.add_argument("--device", default="cuda", help="'cuda' or 'cpu'")

    # PPO
    ap.add_argument("--ppo_zip", required=True, help="Stable-Baselines3 policy .zip path (PPO/A2C/RecurrentPPO)")
    ap.add_argument("--algo", type=str, default="ppo", choices=["ppo","a2c","recurrent_ppo"],
                    help="Algorithm family of the provided .zip weights")
    ap.add_argument("--transpose_nchw", action="store_true",
                    help="Enable if PPO was trained with VecTransposeImage (HWC->CHW).")

    # Prime frames source
    ap.add_argument("--init_npz_glob", default="/home/sdainelli/Aladdin/neurIPS/ground_truth_data/coinrun/myrun/all_frames/*.npz",
                    help="Glob for NPZ episodes to sample a reset frame (same dataset used for training primes)")

    # Rollout config
    ap.add_argument("--episodes", type=int, default=10, help="# episodes to evaluate")
    ap.add_argument("--max_steps", type=int, default=256, help="Max steps per episode")

    # WM sampling
    ap.add_argument("--inference_steps", type=int, default=2, help="WM diffusion/maskgit steps per frame")
    ap.add_argument("--sample_temperature", type=float, default=1.0, help="WM sampling temperature")
    ap.add_argument("--mask_schedule", type=str, default="cosine", help="Mask schedule")

    # Flow-odometry reward params (must match training)
    ap.add_argument("--downscale", type=int, default=64, help="Optical flow longside")
    ap.add_argument("--bottom_bias", type=float, default=2.0, help="Bottom emphasis for weights")
    ap.add_argument("--roi", type=str, default="0.20,0.95,0.05,0.95", help="ROI y0,y1,x0,x1 in [0,1]")
    ap.add_argument("--flow_baseline", type=str, choices=["global","sky","none"], default="sky",
                    help="Residual-flow baseline subtraction mode")
    ap.add_argument("--dx_clip", type=float, default=0.1, help="Clip per-step dx,dy (in normalized units)")
    ap.add_argument("--dx_smooth", type=float, default=0.5, help="EMA smoothing for dx,dy")

    # Goal
    ap.add_argument("--goal_screens", type=float, default=1.0, help="Absolute X goal (in screen widths)")
    ap.add_argument("--goal_xy", type=str, default=None, help="Override goal as 'x_screens,y_frac' (y∈[0,1])")
    ap.add_argument("--goal_y_weight", type=float, default=0.3, help="Weight for Y in distance")
    ap.add_argument("--goal_radius", type=float, default=0.05, help="Success radius (screens)")
    ap.add_argument("--success_bonus", type=float, default=1.0, help="Success bonus")
    ap.add_argument("--reward_scale", type=float, default=5.0, help="Scale for distance delta reward")


    # Output
    ap.add_argument("--save_root", type=str, default="wm_eval_outputs", help="Output root directory")
    ap.add_argument("--dataset_name", type=str, default="coinrun", help="Dataset label for path")
    ap.add_argument("--model_name", type=str, default="GenieRedux_Guided_CoinRun_80mln_v1.0", help="Model label for path")
    ap.add_argument("--top_media", type=int, default=25,
                    help="Number of top-return episodes for which to save GIF/PNG media (0=disable)")

    # Temp
    ap.add_argument("--debug_random", action="store_true", help="Use random actions instead of PPO")

    args = ap.parse_args()

    use_cuda = torch.cuda.is_available() and args.device.startswith("cuda")
    device = torch.device(args.device if use_cuda else "cpu")

    # Build WM
    cfg = load_cfg(args.config)
    wm, image_hw, action_dim, _ = build_world_model(cfg, args.model_ckpt, device, tokenizer_ckpt=args.tokenizer_ckpt)
    # print(f"[WM] image_hw={image_hw}, action_dim={action_dim}")

    # Agent
    algo = args.algo.lower()
    if algo == "ppo":
        policy = PPO.load(args.ppo_zip, device="auto")
    elif algo == "a2c":
        policy = A2C.load(args.ppo_zip, device="auto")
    else:
        policy = RecurrentPPO.load(args.ppo_zip, device="auto")
    # print(f"[POLICY] loaded ({algo}): {args.ppo_zip}")

    # Prime frames
    provider = PrimeProvider(args.init_npz_glob, image_hw)

    # Goal / reward parsing
    if args.goal_xy is not None:
        gx, gy = [float(v.strip()) for v in args.goal_xy.split(",")]
    else:
        gx, gy = float(args.goal_screens), 0.5
    roi = tuple(float(v.strip()) for v in args.roi.split(","))  # y0,y1,x0,x1

    # Output setup
    out_root = Path(args.save_root) / args.dataset_name / args.model_name
    out_root.mkdir(parents=True, exist_ok=True)
    rows = []
    all_rewards = [] # to make an avg reward
    top_media_heap: List[Tuple[float, int, Dict[str, object]]] = []
    top_media_limit = max(0, args.top_media)
    top_media_counter = 0

    for ep_idx in range(args.episodes):
        print(f"[RUN] episode {ep_idx+1}/{args.episodes}")
        try:
            res = run_one_episode_closed_loop(
                wm=wm, policy=policy, device=device, image_hw=image_hw, provider=provider,
                transpose_nchw=args.transpose_nchw,
                inference_steps=args.inference_steps,
                sample_temperature=args.sample_temperature,
                mask_schedule=args.mask_schedule,
                max_steps=args.max_steps,
                downscale=args.downscale, bottom_bias=args.bottom_bias, roi=roi,
                flow_baseline=args.flow_baseline, dx_clip=args.dx_clip, dx_smooth=args.dx_smooth,
                goal_x=gx, goal_y=gy, goal_y_weight=args.goal_y_weight,
                goal_radius=args.goal_radius, success_bonus=args.success_bonus,
                reward_scale=args.reward_scale,
                is_recurrent=(algo == "recurrent_ppo"),
            )
        except Exception as e:
            print(f"[ERROR] episode {ep_idx}: {e}")
            traceback.print_exc()
            continue

        ep_name = f"wmppo_ep{ep_idx:04d}_len{res['len']}"

        # row
        rows.append({
            "episode": ep_name,
            "return": res["return"],
            "len": res["len"],
            "goal_x": gx,
            "goal_y": gy,
        })
        episode_return = float(res["return"])
        print(f"[EP] {ep_name}: return={episode_return:.3f}, steps={res['len']}")
        all_rewards.append(episode_return)

        if top_media_limit > 0:
            top_media_entry = (
                episode_return,
                top_media_counter,
                {
                    "episode": ep_name,
                    "frames": res["frames"],
                },
            )
            top_media_counter += 1
            if len(top_media_heap) < top_media_limit:
                heapq.heappush(top_media_heap, top_media_entry)
            else:
                if episode_return > top_media_heap[0][0]:
                    heapq.heapreplace(top_media_heap, top_media_entry)

    #Avg reward
    if all_rewards:
        avg_return = float(np.mean(all_rewards))
        max_return = float(np.max(all_rewards))
        min_return = float(np.min(all_rewards))
    else:
        avg_return = max_return = min_return = 0.0
    print(f"[RESULT] Average return over {len(all_rewards)} episodes: {avg_return:.3f}")

    # Save media for top episodes only
    if top_media_heap:
        print(f"[MEDIA] Saving GIF/PNG for top {len(top_media_heap)} episode(s)")
        for _, _, media_info in sorted(top_media_heap, key=lambda x: (-x[0], x[1])):
            ep_name = media_info["episode"]
            vid = frames_to_video_tensor(list(media_info["frames"]), image_hw)
            save_dir = out_root / f"samples_wmppo_{ep_name}"
            save_row_gif_png(save_dir, ep_name, vid)
            print(f"[MEDIA] Saved {ep_name} → {save_dir}")

    # CSV summary
    csv_path = out_root / f"{args.model_name}_ppo_wm_eval.csv"
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["episode","return","len","goal_x","goal_y"])
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
        writer.writerow({
            "episode": "AVERAGE",
            "return": f"{avg_return:.3f}",
            "len": "",
            "goal_x": "",
            "goal_y": "",
        })
        writer.writerow({
            "episode": "MAX",
            "return": f"{max_return:.3f}",
            "len": "",
            "goal_x": "",
            "goal_y": "",
        })
        writer.writerow({
            "episode": "MIN",
            "return": f"{min_return:.3f}",
            "len": "",
            "goal_x": "",
            "goal_y": "",
        })
    print(f"[Saved] Summary CSV → {csv_path}")



if __name__ == "__main__":
    main()
